version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=telegram_bot_user
      - POSTGRES_PASSWORD=telegram_bot_pass
      - POSTGRES_DB=telegram_bot_db
    ports:
      - 5433:5432